#!/usr/bin/env python3
# Copyright © 2026 姚金刚. All rights reserved.
# Project: yao-copyright-skill
# Created by: 姚金刚
# Date: 2026-05-16
# X: https://x.com/yaojingang

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path


AUTHOR = "姚金刚"
DEFAULT_DATE = "2026-05-16"
DEFAULT_X_URL = "https://x.com/yaojingang"

CORE_MARKDOWN_ROOT_FILES = {"SKILL.md", "README.md"}
CORE_MARKDOWN_DIRS = {"references", "docs", "prompts", "templates", "examples"}
SCRIPT_EXTENSIONS = {".py", ".sh", ".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs"}
HASH_EXTENSIONS = {".py", ".sh", ".yml", ".yaml", ".toml"}
BLOCK_EXTENSIONS = {".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs"}
CONFIG_EXTENSIONS = {".yml", ".yaml", ".toml"}

SKIP_DIRS = {
    ".git",
    ".hg",
    ".svn",
    ".venv",
    "venv",
    "node_modules",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    "dist",
    "build",
    "coverage",
    "reports",
}
SKIP_FILES = {
    "package.json",
    "package-lock.json",
    "pnpm-lock.yaml",
    "yarn.lock",
    "bun.lockb",
    "Cargo.lock",
    "Pipfile.lock",
    "poetry.lock",
    "uv.lock",
    "tsconfig.json",
    "settings.json",
}
GENERATED_PATTERNS = (
    r"^\s*(#|//|/\*|\*)?\s*@generated\b",
    r"^\s*(#|//|/\*|\*)?\s*auto-generated\b",
    r"^\s*(#|//|/\*|\*)?\s*autogenerated\b",
    r"^\s*(#|//|/\*|\*)?\s*generated by\b",
    r"^\s*(#|//|/\*|\*)?\s*do not edit\b",
)


@dataclass(frozen=True)
class Notice:
    year: str
    project: str
    author: str
    date: str
    x_url: str

    @property
    def lines(self) -> list[str]:
        return [
            f"Copyright © {self.year} {self.author}. All rights reserved.",
            f"Project: {self.project}",
            f"Created by: {self.author}",
            f"Date: {self.date}",
            f"X: {self.x_url}",
        ]

    def render(self, style: str) -> str:
        if style == "markdown":
            return "<!--\n" + "\n".join(self.lines) + "\n-->\n\n"
        if style == "block":
            return "/**\n" + "\n".join(f" * {line}" for line in self.lines) + "\n */\n\n"
        return "\n".join(f"# {line}" for line in self.lines) + "\n\n"


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Add Yao copyright comment notices to a skill package."
    )
    parser.add_argument("skill_dir", type=Path, help="Target skill directory")
    parser.add_argument(
        "--scope",
        choices=("core", "all"),
        default="core",
        help="core adds core Markdown files; all also adds scripts and YAML/TOML files.",
    )
    parser.add_argument(
        "--project",
        help="Project field. Defaults to the target skill directory name.",
    )
    parser.add_argument("--date", default=DEFAULT_DATE, help="Notice date")
    parser.add_argument("--year", help="Copyright year. Defaults to the date year.")
    parser.add_argument("--author", default=AUTHOR, help="Notice author")
    parser.add_argument("--x-url", default=DEFAULT_X_URL, help="X profile URL")
    parser.add_argument("--dry-run", action="store_true", help="Report changes only")
    return parser.parse_args(argv)


def is_under_skipped_dir(path: Path, root: Path) -> bool:
    rel = path.relative_to(root)
    return any(part in SKIP_DIRS for part in rel.parts[:-1])


def looks_generated(path: Path) -> bool:
    try:
        lines = path.read_text(encoding="utf-8").splitlines()[:12]
    except UnicodeDecodeError:
        return True
    return any(
        re.search(pattern, line.lower())
        for line in lines
        for pattern in GENERATED_PATTERNS
    )


def is_core_markdown(path: Path, root: Path) -> bool:
    rel = path.relative_to(root)
    if path.suffix.lower() != ".md":
        return False
    if len(rel.parts) == 1 and path.name in CORE_MARKDOWN_ROOT_FILES:
        return True
    return bool(rel.parts and rel.parts[0] in CORE_MARKDOWN_DIRS)


def comment_style(path: Path, root: Path, scope: str) -> str | None:
    rel = path.relative_to(root)
    if path.name in SKIP_FILES or path.suffix.lower() == ".json" or path.name.endswith(".lock"):
        return None
    if is_under_skipped_dir(path, root):
        return None

    suffix = path.suffix.lower()
    if is_core_markdown(path, root):
        return "markdown"
    if scope == "all" and len(rel.parts) > 1 and rel.parts[0] == "scripts" and suffix in SCRIPT_EXTENSIONS:
        return "block" if suffix in BLOCK_EXTENSIONS else "hash"
    if scope == "all" and suffix in CONFIG_EXTENSIONS:
        return "hash"
    return None


def has_existing_notice(text: str, path: Path, style: str, author: str) -> bool:
    if style == "markdown":
        index = markdown_insert_index(text)
    else:
        index = script_insert_index(text, path.suffix.lower())
    sample = text[index : index + 500].lstrip()
    if style == "markdown":
        return sample.startswith("<!--") and "Copyright ©" in sample[:120] and author in sample[:240]
    if style == "block":
        return sample.startswith("/**") and "Copyright ©" in sample[:160] and author in sample[:260]
    return sample.startswith("# Copyright ©") and author in sample[:200]


def markdown_insert_index(text: str) -> int:
    if not text.startswith("---\n"):
        return 0

    lines = text.splitlines(keepends=True)
    for index in range(1, len(lines)):
        if lines[index].strip() == "---":
            insert_after = index + 1
            if insert_after < len(lines) and lines[insert_after].strip() == "":
                insert_after += 1
            return sum(len(line) for line in lines[:insert_after])
    return 0


def script_insert_index(text: str, suffix: str) -> int:
    lines = text.splitlines(keepends=True)
    index = 0
    if lines and lines[0].startswith("#!"):
        index = 1
    if suffix == ".py" and index < len(lines):
        if re.match(r"#.*coding[:=]\s*[-\w.]+", lines[index]):
            index += 1
    return sum(len(line) for line in lines[:index])


def insert_notice(text: str, path: Path, style: str, notice: Notice) -> str:
    rendered = notice.render(style)
    if style == "markdown":
        index = markdown_insert_index(text)
    else:
        index = script_insert_index(text, path.suffix.lower())
    return text[:index] + rendered + text[index:]


def iter_candidate_files(root: Path) -> list[Path]:
    return sorted(path for path in root.rglob("*") if path.is_file())


def process_file(path: Path, root: Path, scope: str, notice: Notice, dry_run: bool) -> str | None:
    style = comment_style(path, root, scope)
    if style is None:
        return None
    if looks_generated(path):
        return f"[skip] {path.relative_to(root)} generated-or-binary"

    text = path.read_text(encoding="utf-8")
    if has_existing_notice(text, path, style, notice.author):
        return f"[skip] {path.relative_to(root)} existing-notice"

    updated = insert_notice(text, path, style, notice)
    action = "[dry-run]" if dry_run else "[write]"
    if not dry_run:
        path.write_text(updated, encoding="utf-8")
    return f"{action} {path.relative_to(root)}"


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    root = args.skill_dir.expanduser().resolve()
    if not root.is_dir():
        print(f"error: skill_dir is not a directory: {root}", file=sys.stderr)
        return 2

    year = args.year or args.date[:4]
    project = args.project or root.name
    notice = Notice(
        year=year,
        project=project,
        author=args.author,
        date=args.date,
        x_url=args.x_url,
    )

    results = []
    for path in iter_candidate_files(root):
        result = process_file(path, root, args.scope, notice, args.dry_run)
        if result:
            results.append(result)

    for result in results:
        print(result)
    print(f"summary: {len([r for r in results if r.startswith('[write]') or r.startswith('[dry-run]')])} change(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
